# Generated by Django 6.0.3 on 2026-03-14 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('kreirana', models.DateTimeField(auto_now_add=True)),
                ('procitana', models.BooleanField(default=False)),
                ('posiljalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poslate_poruke', to=settings.AUTH_USER_MODEL)),
                ('primalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primljene_poruke_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kreirana'],
            },
        ),
    ]
