# Generated by Django 6.0.3 on 2026-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('starost', models.PositiveIntegerField(help_text='Starost u godinama')),
                ('tezina', models.DecimalField(decimal_places=2, help_text='Tezina u kg', max_digits=5)),
                ('velicina', models.CharField(choices=[('mali', 'Mali (do 10kg)'), ('srednji', 'Srednji (10-25kg)'), ('veliki', 'Veliki (25kg+)')], max_length=10)),
                ('pol', models.CharField(choices=[('muz', 'Muz'), ('zenka', 'Zenka')], max_length=10)),
                ('sterilizovan', models.BooleanField(default=False)),
                ('temperament', models.CharField(blank=True, help_text='npr. miran, energican, agresivan prema psima', max_length=255)),
                ('posebne_napomene', models.TextField(blank=True, help_text='Alergije, lekovi, strahovi...')),
                ('slika', models.ImageField(blank=True, null=True, upload_to='psi/')),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pas',
                'verbose_name_plural': 'Psi',
            },
        ),
    ]
