# Generated by Django 6.0.3 on 2026-04-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='weight',
        ),
    ]
