# Generated by Django 6.0.3 on 2026-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_usluge', models.CharField(choices=[('setanje', 'Setanje'), ('cuvanje', 'Cuvanje')], max_length=10)),
                ('datum_od', models.DateTimeField()),
                ('datum_do', models.DateTimeField()),
                ('status', models.CharField(choices=[('na_cekanju', 'Na cekanju'), ('potvrdjeno', 'Potvrdjeno'), ('odbijeno', 'Odbijeno'), ('zavrseno', 'Zavrseno'), ('otkazano', 'Otkazano')], default='na_cekanju', max_length=15)),
                ('napomena', models.TextField(blank=True)),
                ('kreirana', models.DateTimeField(auto_now_add=True)),
                ('azurirana', models.DateTimeField(auto_now=True)),
                ('psi', models.ManyToManyField(related_name='rezervacije', to='dogs.pas')),
            ],
            options={
                'verbose_name': 'Rezervacija',
                'verbose_name_plural': 'Rezervacije',
                'ordering': ['-kreirana'],
            },
        ),
    ]
