# Generated by Django 6.0.3 on 2026-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacija',
            name='trajanje',
            field=models.PositiveIntegerField(blank=True, help_text='Trajanje u minutima (20, 30, 60)', null=True),
        ),
        migrations.AlterField(
            model_name='rezervacija',
            name='tip_usluge',
            field=models.CharField(choices=[('setanje', 'Setanje'), ('cuvanje', 'Cuvanje'), ('drop_in', 'Drop-in poseta')], max_length=10),
        ),
    ]
