# Generated by Django 6.0.3 on 2026-03-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rezervacija_trajanje_alter_rezervacija_tip_usluge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervacija',
            name='tip_usluge',
            field=models.CharField(choices=[('setanje', 'Setanje'), ('cuvanje', 'Cuvanje')], max_length=10),
        ),
    ]
