# Generated by Django 6.0.3 on 2026-03-14 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('komentar', models.TextField(blank=True)),
                ('kreirana', models.DateTimeField(auto_now_add=True)),
                ('rezervacija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recenzija', to='reservations.rezervacija')),
            ],
            options={
                'verbose_name': 'Recenzija',
                'verbose_name_plural': 'Recenzije',
                'ordering': ['-kreirana'],
            },
        ),
    ]
