# Generated by Django 6.0.3 on 2026-03-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzija',
            name='setac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primljene_recenzije', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recenzija',
            name='vlasnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_recenzije', to=settings.AUTH_USER_MODEL),
        ),
    ]
