# Generated by Django 6.0.3 on 2026-03-14 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('broj_telefona', models.CharField(blank=True, max_length=20)),
                ('profilna_slika', models.ImageField(blank=True, null=True, upload_to='profili/')),
                ('tip', models.CharField(choices=[('vlasnik', 'Vlasnik psa'), ('setac', 'Setac/Cuvar'), ('admin', 'Administrator')], default='vlasnik', max_length=10)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Korisnik',
                'verbose_name_plural': 'Korisnici',
            },
        ),
        migrations.CreateModel(
            name='SetacProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_po_satu', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usluge', models.CharField(choices=[('setanje', 'Setanje'), ('cuvanje', 'Cuvanje'), ('oba', 'Setanje i cuvanje')], default='oba', max_length=10)),
                ('opis', models.TextField(blank=True)),
                ('aktivan', models.BooleanField(default=True)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setac_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setac profil',
                'verbose_name_plural': 'Setac profili',
            },
        ),
    ]
