# Generated by Django 6.0.3 on 2026-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_lat_user_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setacprofil',
            name='usluge',
            field=models.CharField(choices=[('setanje', 'Setanje'), ('cuvanje', 'Cuvanje'), ('drop_in', 'Drop-in poseta'), ('oba', 'Sve usluge')], default='oba', max_length=10),
        ),
    ]
