# Generated by Django 6.0.3 on 2026-03-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_setacprofil_usluge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setacprofil',
            name='usluge',
            field=models.CharField(choices=[('setanje', 'Setanje'), ('cuvanje', 'Cuvanje'), ('oba', 'Sve usluge')], default='oba', max_length=10),
        ),
    ]
