# Generated by Django 6.0.3 on 2026-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_setacprofil_usluge'),
    ]

    operations = [
        migrations.AddField(
            model_name='setacprofil',
            name='dostupnost',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
