# Generated by Django 6.0.3 on 2026-03-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_walkerprofile_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkerprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
